### ISSUE TITLE
Replica-dataset

### ISSUE THREAD

**Issue by Zuriich** [DLR-RM/SingleViewReconstruction#7]
Hi,
First, thank you for your great Paper, I really enjoyed reading it.
I am currently trying the network with the SUNCG dataset, but as you mention in the paper you also used the Replica dataset to evaluate your network, could you provide some input on how you did this? By that I mean: data adaptation/generation, evaluation script on the different datasets, etc. Every input on this matter is more than welcome.
Thank you very much for your great work.

**Comment by themasterlink** [comment]
Hey,

thanks!

>  By that I mean: data adaptation/generation, evaluation script on the different datasets, etc. Every input on this matter is more than welcome.

I used exactly the same evaluation script as the output is of course the same as in the SUNCG case. The only difference was the input. Here I used BlenderProc for generating the normal images and I have rewritten the Replica-Dataset API to output some images, so that they use the same format used in the SDFGen. If you want I could add this part to this repository.

The sampling of the poses, I also did in with BlenderProc. I only needed to use the Replica-Dataset API has BlenderProc has no full color support for Replica, as they save their textures in HDRI format, which we didn't work in blender at all.

Sorry for the late reply.

Best,
Max
